services:
  postgres-config:
    image: postgres:alpine
    environment:
      POSTGRES_DB: config_db
      POSTGRES_USER: config_user
      POSTGRES_PASSWORD: config_pass
    ports:
      - "5432:5432"
    volumes:
      - config_db_data:/var/lib/postgresql/data
      - ./config_db.sql:/docker-entrypoint-initdb.d/config_db.sql  # Mount SQL script
    networks:
      - app-network

  postgres-factory:
    image: postgres:alpine
    environment:
      POSTGRES_DB: factory_db
      POSTGRES_USER: factory_user
      POSTGRES_PASSWORD: factory_pass
    ports:
      - "5433:5432"
    volumes:
      - factory_db_data:/var/lib/postgresql/data
      - ./factory_db.sql:/docker-entrypoint-initdb.d/factory_db.sql  # Mount SQL script
    networks:
      - app-network

volumes:
  config_db_data:
  factory_db_data:

networks:
  app-network:
